[package]
name = "icfpc2018_lib"
version = "0.4.2"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[dependencies]
rtt = "0.4"
rand = "0.5"
kdvtree = "0.8"
bit-vec = "0.5"
pathfinding = "0.8"
itertools = "0.7.8"
