[package]
name = "icfpc2018_lib"
version = "0.7.2"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[dependencies]
log = "0.4"
rtt = "0.4"
rand = "0.5"
rayon = "1.0"
kdvtree = "0.8"
bit-vec = "0.5"
pathfinding = "0.8"
itertools = "0.7.8"
