[package]
name = "trace-gravitizer"
version = "0.1.0"
authors = ["Gleb Golubitsky <sectoid@gnolltech.org>","merl <merl.001.mia@gmail.com>"]

[dependencies]
icfpc2018_lib = { path = "../icfpc2018_lib" }
clap = "2.31"
